seasons:
  spring:
    duration: 10  # Продолжительность сезона в игровых днях
    weather:
      rain_chance: 50  # Вероятность дождя в процентах
      storm_chance: 20  # Вероятность грозы в процентах

  summer:
    duration: 10
    weather:
      rain_chance: 10
      storm_chance: 5

  autumn:
    duration: 10
    weather:
      rain_chance: 60
      storm_chance: 30

  winter:
    duration: 10
    weather:
      snow_chance: 70
      storm_chance: 40
